from Singly_LinkedList import Singly_LinkedList
from Doubly_LinkedList import Doubly_LinkedList

singly_linked_list = Singly_LinkedList()
singly_linked_list.insert_first(1)
singly_linked_list.insert_last(2)
singly_linked_list.insert_last(3)
singly_linked_list.insert_last(4)
singly_linked_list.insert_last(5)
singly_linked_list.insert_last(6)

# print(new_node.head.data)
singly_linked_list.remove_first()
singly_linked_list.remove_last()
singly_linked_list.remove_at(3)
singly_linked_list.insert_at(4, 3)
# singly_linked_list.print()
# print(new_node.length())

doubly_linked_list = Doubly_LinkedList()
doubly_linked_list.insert_first(4)
doubly_linked_list.insert_first(3)
doubly_linked_list.insert_first(2)
doubly_linked_list.insert_first(1)
doubly_linked_list.insert_at(4, 2)
doubly_linked_list.remove_at(3)
# doubly_linked_list.remove_first()
# doubly_linked_list.remove_last()
doubly_linked_list.print_descending()
doubly_linked_list.print_ascending()